# Generated by Django 5.2.1 on 2025-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bus_images/'),
        ),
        migrations.AddField(
            model_name='bus',
            name='pickup_place',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
