# Generated by Django 5.2.1 on 2025-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='reach_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
