# Generated by Django 5.2.1 on 2025-05-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bus_reach_time_alter_bus_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='reach_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
